// Generates an app-sized import graph: COUNT modules, imported through chunk
// barrels the way a real app's dependencies are, so every module is evaluated
// while the dev bundle starts up. Each module is roughly the size of a small
// source file in a real app.
//
// Run with: node scripts/generate-modules.mjs [count]
import { mkdirSync, rmSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const COUNT = Number(process.argv[2] ?? 24000);
const CHUNK = 500;

const modules = join(dirname(fileURLToPath(import.meta.url)), '..', 'modules');
rmSync(modules, { recursive: true, force: true });
mkdirSync(modules, { recursive: true });

const range = (n) => Array.from({ length: n }, (_, i) => i);
const chunkCount = Math.ceil(COUNT / CHUNK);

const moduleSource = (i) => `export type Options${i} = {
  id: number;
  label: string;
  enabled: boolean;
  weights: number[];
};

export const defaults${i}: Options${i} = {
  id: ${i},
  label: 'module-${i}',
  enabled: ${i % 2 === 0},
  weights: [${range(8)
    .map((w) => i + w)
    .join(', ')}],
};

export function scale${i}(x: number): number {
  let y = x + ${i};
  y = y * 2 - ${i};
  return y ^ ${i % 97};
}

export function combine${i}(values: number[]): number {
  let total = 0;
  for (const value of values) {
    total += scale${i}(value);
  }
  return total;
}

export function describe${i}(options: Options${i} = defaults${i}): string {
  const parts = [options.label, String(options.id), options.enabled ? 'on' : 'off'];
  return parts.join(':');
}

export function pick${i}(options: Options${i}, index: number): number {
  const { weights } = options;
  if (index < 0 || index >= weights.length) {
    return combine${i}(weights);
  }
  return scale${i}(weights[index]);
}

export function reduce${i}(options: Options${i} = defaults${i}): Record<string, number> {
  const out: Record<string, number> = {};
  options.weights.forEach((weight, index) => {
    out[\`w\${index}\`] = pick${i}(options, index) + weight;
  });
  return out;
}

export default function m${i}(x: number): number {
  return combine${i}([x, scale${i}(x), pick${i}(defaults${i}, x % 8)]);
}
`;

for (const i of range(COUNT)) {
  writeFileSync(join(modules, `m${i}.ts`), moduleSource(i));
}

for (const c of range(chunkCount)) {
  const ids = range(Math.min(CHUNK, COUNT - c * CHUNK)).map((i) => c * CHUNK + i);
  writeFileSync(
    join(modules, `chunk${c}.ts`),
    `// Generated by scripts/generate-modules.mjs. Do not edit.
${ids.map((i) => `import m${i} from './m${i}';`).join('\n')}

export const fns: ((x: number) => number)[] = [${ids.map((i) => `m${i}`).join(', ')}];
`
  );
}

writeFileSync(
  join(modules, 'index.ts'),
  `// Generated by scripts/generate-modules.mjs. Do not edit.
${range(chunkCount)
  .map((c) => `import { fns as fns${c} } from './chunk${c}';`)
  .join('\n')}

export const MODULE_COUNT = ${COUNT};

export const fns: ((x: number) => number)[] = [
${range(chunkCount)
  .map((c) => `  ...fns${c},`)
  .join('\n')}
];
`
);

console.log(`Generated ${COUNT} modules in ${chunkCount} chunks`);
